export const devicesList: any[] = [
  {
    id: "1",
    name: "iphone-11",
    price: 999,
    tags: ["iPhone"],
    favorite: true,
    stars: 4.5,
    imageUrl: "assets\\iphone-11.jpg",
    origins: ["USA", "China"],
  },
  {
    id: "2",
    name: "ipad-air",
    price: 1099,
    tags: ["iPad"],
    favorite: false,
    stars: 4.2,
    imageUrl: "assets\\ipad-air.jpg",
    origins: ["USA", "China"],
  },
  {
    id: "3",
    name: "iphone-13",
    price: 799,
    tags: ["iPhone"],
    favorite: true,
    stars: 4.7,
    imageUrl: "assets\\iphone-13.jpg",
    origins: ["USA", "China"],
  },
  {
    id: "4",
    name: "ipad-mini",
    price: 699,
    tags: ["iPad"],
    favorite: false,
    stars: 4.0,
    imageUrl: "assets\\ipad-mini.jpg",
    origins: ["USA", "China"],
  },
  {
    id: "5",
    name: "iphone-12",
    price: 399,
    tags: ["iPhone"],
    favorite: true,
    stars: 4.3,
    imageUrl: "assets\\iphone-12.png",
    origins: ["USA", "China"],
  },
  {
    id: "6",
    name: "ipad-pro12",
    price: 399,
    tags: ["iPad"],
    favorite: false,
    stars: 4.1,
    imageUrl: "assets\\ipad-pro12.jpg",
    origins: ["USA", "China"],
  },
  {
    id: "7",
    name: "iphone-14",
    price: 1099,
    tags: ["iPhone"],
    favorite: true,
    stars: 4.8,
    imageUrl: "assets\\iphone-14.jpg",
    origins: ["USA", "China"],
  },
  {
    id: "8",
    name: "ipad-pro11",
    price: 1299,
    tags: ["iPad"],
    favorite: false,
    stars: 4.9,
    imageUrl: "assets\\ipad-pro11.jpg",
    origins: ["USA", "China"],
  },
];

export const tagList: any[] = [
  { name: "All", count: 8 },
  { name: "iPhone", count: 4 },
  { name: "iPad", count: 4 },
];

export const usersList: any[] = [
  {
    name: "tamir haspel",
    email: "tamir@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "alaa",
    email: "alaa@gmail.com",
    password: "12345",
    address: "beth-jan",
    isAdmin: false,
  },
];
